# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: Rust Unit Tests

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - run: cd hc-dna/
    - run: cargo test -- --test-threads=1

  pull:
    name: Pull

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-pull

  render:
    name: Render

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-render

  revisions:
    name: Revisions

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: npm install -g npm && cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-revisions

  signals:
    name: Signals

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: npm install -g npm && cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-signals


  stress:
    name: Stress

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: npm install -g npm && cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-stress

  telepresence:
    name: Telepresence

    strategy:
      matrix:
        platform: [ubuntu-22.04]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rustup target add wasm32-unknown-unknown
    - run: npm install -g npm
    - run: cd hc-dna/zomes/tests && ./download-hc-binaries.sh
    - run: cargo install --version 0.2.3 lair_keystore || echo "lair already installed"
    - run: npm install -g npm && cd hc-dna/zomes/tests && npm i && npm run build-ci && npm run test-telepresence